## SIMPLE REGRESSION

In [7]:
! pip install numpy pandas scikit-learn matplotlib

Requirement already satisfied: numpy in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.26.3)
Requirement already satisfied: pandas in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (2.1.3)
Requirement already satisfied: scikit-learn in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (1.3.2)
Requirement already satisfied: matplotlib in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (3.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.5.0 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (1.16.1)
Requirement already satisfied: joblib>=1.1.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (4.59.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: pyparsing>=2.3.1 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: six>=1.5 in C:\Users\Suryaprakash\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Suryaprakash\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

### import the libraries

In [8]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

### Perform statistical analysis

In [10]:
df = pd.read_csv("C:\\Users\\Suryaprakash\\OneDrive\\Documents\\Python\\ML - basics\\salary_dataset.csv")

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes

In [12]:
df.describe()

       Unnamed: 0  YearsExperience         Salary
count   30.000000        30.000000      30.000000
mean    14.500000         5.413333   76004.000000
std      8.803408         2.837888   27414.429785
min      0.000000         1.200000   37732.000000
25%      7.250000         3.300000   56721.750000
50%     14.500000         4.800000   65238.000000
75%     21.750000         7.800000  100545.750000
max     29.000000        10.600000  122392.000000

In [ ]:
df.head()   ## first five value of dataset

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
df.tail()  ## last five values of dataset

    Unnamed: 0  YearsExperience    Salary
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [ ]:
df.isnull()   ## to check null values

    Unnamed: 0  YearsExperience  Salary
0        False            False   False
1        False            False   False
2        False            False   False
3        False            False   False
4        False            False   False
5        False            False   False
6        False            False   False
7        False            False   False
8        False            False   False
9        False            False   False
10       False            False   False
11       False            False   False
12       False            False   False
13       False            False   False
14       False            False   False
15       False            False   False
16       False            False   False
17       False            False   False
18       False            False   False
19       False            False   False
20       False            False   False
21       False            False   False
22       False            False   False
23       False            False   False
24       False            False   False
25       False            False   False
26       False            False   False
27       False            False   False
28       False            False   False
29       False            False   False

In [ ]:
df.isnull().sum()  ##sum of null values in each column

Unnamed: 0         0
YearsExperience    0
Salary             0
dtype: int64

In [ ]:
df.shape  # it gives the number of rows and columns in dataset

(30, 3)